### ISSUE TITLE
tab completion hangs

### ISSUE THREAD

**Issue by rightisleft** [edouard-lopez/yeoman-zsh-plugin#5]
typing yo<tab>  causes a 5-10 second hang where the terminal window becomes unresponsive on oh-my-zsh

**Comment by edouard-lopez** [comment]
I've a bottlenet due to the way I [get the generator's description](https://github.com/edouard-lopez/yeoman-zsh-plugin/blob/f7c9f7322e0337cdfd8ab05d226bad71c1603507/helpers_yo#L76):

    npm view --silent "$packageInfo" description &

I'm not familiar enough with `npm` to know if it's can be improved easily. Poke me if you've suggestion.
