### ISSUE TITLE
bug: Tab completion gives empty string as a possible generator

### ISSUE THREAD

**Issue by Yash-Singh1** [edouard-lopez/yeoman-zsh-plugin#9]
![Screenshot from 2021-12-29 18-08-52](https://user-images.githubusercontent.com/53054099/147716066-8a20246a-d638-4b28-8572-25fa3fb59540.png)

```
Available Generators  -- :Available Generators:'s generator
eslint-config         -- eslint-config's generator
github-action         -- github-action's generator
license               -- license's generator
                      -- 's generator
webapp                -- Default Yeoman generator for scaffolding out a front-end web app
```

**Comment by edouard-lopez** [comment]
@Yash-Singh1 Thanks for the feedback, it made me realized I haven't used `yeoman`  for a couple of years now. 

If you submit a pull request I will review it with pleasure, otherwise I will archive the repo as I'm not working on it anymore.

**Comment by edouard-lopez** [comment]
The behavior is controlled in `helpers_yo` file:
https://github.com/edouard-lopez/yeoman-zsh-plugin/blob/1019f36111a5f94adb63990dd0befce22c5ec4c2/helpers_yo#L65-L79

**Comment by Yash-Singh1** [comment]
I will give this a shot later.

**Comment by Yash-Singh1** [comment]
I created #10 with a fix for this issue.
